train:
  experiment_name: 'semantic_sam'

  # Model
  model:
    sam_name: 'pneu_sam'
    params:
      ckpt_path: 'sam_ckpt/sam_vit_b_01ec64.pth'
      model_type: 'vit_b'
  
  # Dataset
  dataset:
    name: 'PneumothoraxDataset'
    params:
      dataset_dir: 'input/dataset1024'
      image_set: 'train'
    transforms:
      resize:
        params:
          size: [1024, 1024]
      to_tensor:
        params: ~
    target_transforms:
      resize:
        params:
          size: [1024, 1024]
        
    # Sampler
  sampler:
    name: 'PneumoSampler'
    params:
      dataset_dir: 'input/dataset1024'
      image_set: 'train'
      demand_non_empty_prob: 0.8

  # Losses
  losses:
    combo_loss:
      weight: 1.0
      params: 
        weights:
          bce: 3          
          focal: 4
          dice: 1  # ~ means None type, the initial params of loss could be identified here
      #   ignore_index: 255
      # label_one_hot: False

  # Optimizer
  opt_params:
    lr_default:  5e-4
    wd_default: 5e-6
    # momentum: 0.9
    lr_list:  [ 5e-4, ]
    group_keys: [ [ 'ori_sam.image_encoder', 'mask_adapter.decoder_head.output_hypernetworks_mlps', ], ]
    wd_list:  [ 0.0, ]

  opt_name: 'adam' # 'sgd'
  scheduler_name: 'single_step'

  # Runner
  max_iter: 15000
  log_iter: 500
  eval_iter: 500
  runner_name: 'sem_runner'
  # Dataloader
  bs: 2 # 8
  num_workers: 2
  drop_last: True
  # Logger
  use_tensorboard: True
  tensorboard_folder: './experiment/tensorboard'
  log_folder: './experiment/log'
  model_folder: './experiment/model'

val:
  # Dataset
  dataset:
    name: 'PneumothoraxDataset'
    params:
      dataset_dir: 'input/dataset1024'
      image_set: 'val'
    transforms:
      resize:
        params:
          size: [1024, 1024]
      to_tensor:
        params: ~
    target_transforms:
      resize:
        params:
          size: [1024, 1024]

  bs: 2
  num_workers: 2
  drop_last: True


test:
  need_test: True

mask_binarizer:
  name: TripletMaskBinarization
  params:
    triplets:
      [
        [0.75, 1000, 0.3],
        [0.75, 1000, 0.4],
        [0.75, 2000, 0.3],
        [0.75, 2000, 0.4],
        [0.6, 2000, 0.3],
        [0.6, 2000, 0.4],
        [0.6, 3000, 0.3],
        [0.6, 3000, 0.4],
      ]
